name: Build HANGY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install customtkinter pillow pygame pyinstaller

      - name: Build executable
        run: |
          pyinstaller --windowed --name HANGY ^
          --add-data "images;images" ^
          --add-data "music;music" ^
          --add-data "words.txt;." ^
          --add-data "saves;saves" ^
          hangman.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HANGY-Windows
          path: dist
